import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SocialMedia from "./1_components/socialMedia/SocialMedia";
import SocialMedia2 from "./1_components/socialMedia2/SocialMedia2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <SocialMedia2 className="footer2" />
        <SocialMedia className="footer" />
      </body>
    </html>
  );
}
